// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arphqcjrmqigllafrzcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycGhxY2pybXFpZ2xsYWZyemNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTAyNDAsImV4cCI6MjA2ODg2NjI0MH0.8kn0A3UaAlSwskV80gidjwf4LJSmGZB13i0jNt5YgUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});